#!/usr/bin/env python3
"""Regenerate the auto-updated sections of the GitHub Pages homepage.

Fetches the user's recently starred repositories and recently pushed
repositories from the GitHub API, then rewrites the content between the
<!-- STARS:START/END -->, <!-- REPOS:START/END --> and
<!-- UPDATED:START/END --> markers in index.html.

Requires the GITHUB_TOKEN environment variable (provided automatically in
GitHub Actions). No third-party dependencies.
"""

import html
import json
import os
import re
import sys
import urllib.request
from datetime import datetime, timezone

USER = os.environ.get("GITHUB_USER", "UnknownObject777")
INDEX = os.path.join(os.path.dirname(__file__), "..", "index.html")

STARS_LIMIT = 10
REPOS_LIMIT = 8


def gh_api(path, accept="application/vnd.github+json"):
    req = urllib.request.Request(
        f"https://api.github.com{path}",
        headers={
            "Accept": accept,
            "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
            "X-GitHub-Api-Version": "2022-11-28",
            "User-Agent": "homepage-updater",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)


def esc(text):
    return html.escape((text or "").strip(), quote=False)


def render_stars():
    items = gh_api(
        f"/users/{USER}/starred?per_page={STARS_LIMIT}",
        accept="application/vnd.github.star+json",
    )
    rows = ['<div class="idx">']
    for item in items:
        repo = item["repo"]
        desc = esc(repo.get("description"))
        lang = esc(repo.get("language")) or "—"
        stars = f"{repo['stargazers_count']:,}"
        rows.append(
            f'  <a class="idx-row" href="{repo["html_url"]}" target="_blank" rel="noopener">\n'
            f'    <span class="name">{esc(repo["full_name"])}</span>\n'
            f'    <span class="desc">{desc}</span>\n'
            f'    <span class="meta">{lang} · <b>★ {stars}</b></span>\n'
            '  </a>'
        )
    rows.append('</div>')
    return "\n".join(rows)


def render_repos():
    repos = gh_api(f"/users/{USER}/repos?sort=pushed&per_page={REPOS_LIMIT}")
    rows = ['<div class="idx">']
    for repo in repos:
        desc = esc(repo.get("description"))
        lang = esc(repo.get("language")) or "—"
        pushed = repo["pushed_at"][:10]
        rows.append(
            f'  <a class="idx-row" href="{repo["html_url"]}" target="_blank" rel="noopener">\n'
            f'    <span class="name">{esc(repo["name"])}</span>\n'
            f'    <span class="desc">{desc}</span>\n'
            f'    <span class="meta">{lang} · <b>{pushed}</b></span>\n'
            '  </a>'
        )
    rows.append('</div>')
    return "\n".join(rows)


def render_updated():
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f'<span>last updated {now} · auto-generated by <a href="https://github.com/{USER}/{USER}.github.io/actions">GitHub Actions</a></span>'


def replace_block(content, tag, body):
    pattern = re.compile(
        rf"(<!-- {tag}:START -->\n).*?(<!-- {tag}:END -->)", re.DOTALL
    )
    if not pattern.search(content):
        sys.exit(f"error: marker {tag} not found in index.html")
    return pattern.sub(rf"\1{body}\n\2", content)


def main():
    with open(INDEX, encoding="utf-8") as f:
        content = f.read()
    content = replace_block(content, "STARS", render_stars())
    content = replace_block(content, "REPOS", render_repos())
    content = replace_block(content, "UPDATED", render_updated())
    with open(INDEX, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("index.html updated.")


if __name__ == "__main__":
    main()
